project:
  type: website

execute: 
  freeze: auto

bibliography: references.bib

website:
  title: "CFC Wiki"
  repo-url: https://github.com/hollisakins/cfc/
  repo-actions: [edit]
  navbar:
    logo: images/CFC-LOGO-2color-only.png
    background: primary
    search: true
    right:
      - text: "Contributing"
        href: quickstart.qmd
      - icon: github
        href: https://github.com/hollisakins/cfc/
        target: _blank

  sidebar: 
    - title: "Home"
      collapse-level: 1
      contents:
        - index.qmd
        - text: "Recent Pages"
          href: recents.qmd
        - text: "Contributing"
          href: quickstart.qmd
        - text: "---"
        - section: Pages
          contents: 
            - text: "All Pages"
              href: pages.qmd
            - section: Telescopes & Instruments 
              contents: pages/telescopes/*
    
  back-to-top-navigation: true
  # margin-header: |
    # ![](images/CFC-LOGO-2color.png)
  # body-footer: |
  #   Last updated {{<meta date-modified>}} by {{<meta author>}}.
  #   ![](images/CFC-LOGO-2color.png){.external width="200px"}
  #   [![GitHub](https://img.shields.io/github/stars/hollisakins/cfc?style=social)](

format:
  html:
    theme: 
      light: assets/theme-light.scss
      dark: assets/theme-dark.scss
    css: assets/styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/light.theme
      dark: assets/dark.theme
    sidebar: true
    toc: true
    toc-location: right
    from: markdown+emoji
    reference-location: document
    citation-location: document
    #smooth-scroll: true
    link-external-newwindow: true

